version: '3.1'

services:

  postgres-db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: db-digital-gym
    ports:
      - 5432:5432
    volumes:
      - ../postgres_data:/var/lib/postgres